### ISSUE TITLE
Suggestion: add nestjs support

### ISSUE THREAD

**Issue by omermorad** [auth0/express-openid-connect#221]
### Describe the problem you'd like to have solved

To add support of `express-openid-connect` with NestJS

### Describe the ideal solution

Create a new repository under `auth0`, thus, developers would love to contribute - I will be the first :)

**Comment by adamjmcgrath** [comment]
Great suggestion - thanks @omermorad 

We'd love to extend this code to more frameworks, and in fact our Next.js SDK is [based on this code](https://github.com/auth0/nextjs-auth0/tree/main/src/auth0-session)

I'll leave this open for the time being, so we can consider this as part of our prioritisation

**Comment by omermorad** [comment]
Hi @adamjmcgrath

The need came when I wanted to use `express-openid-connect` with NestJS microservice architecture and I noticed there is no package for it (cause it's brand new).

I thought that maybe I can write it myself (with full coverage) and let you make it official if you guys are interested.

Cheers

**Comment by adamjmcgrath** [comment]
Hi @omermorad - thank you for the kind offer.

We don't have NestJS support in our roadmap currently, but we are always reviewing this based on demand.

You're welcome to create something yourself, but we don't tend to take on community run projects - so it's likely you'd have to own it yourself.

Since this story is not directly releated to the express SDK, I'm going to closee it.

If you want to continue the discussion about NestJS support, I recommend you do this in our Feedback Community https://community.auth0.com/c/feedback/95

**Comment by omermorad** [comment]
Thanks, @adamjmcgrath, I will open a discussion there 👍🏻

**Comment by KieronWiltshire** [comment]
@omermorad did u ever find a solution? I need this too.
