### ISSUE TITLE
I would like to be able to set errorOnRequiredAuth in the requiresAuth middleware instead of in the auth middleware.

### ISSUE THREAD

**Issue by mostekcm** [auth0/express-openid-connect#264]
### Describe the problem you'd like to have solved

I am building a webapp that also has some SPA qualities on certain pages. I want to be able to do frontend to backend calls for certain endpoints without doing a full refresh. To do this though, I want to be able to set certain endpoints to errorOnRequiredAuth and some to just return a 401 so I can trigger the redirect from the frontend. With the current setup, it is much harder to do that because I have to set errorOnRequiredAuth at the auth middleware instead of the requiresAuth middleware.

### Describe the ideal solution

Ideally I'd be able to set a default in the auth middleware and override it in the requiresAuth middleware.

## Alternatives and current work-arounds

The current workaround is to replace the entire res.oidc with a new one and override the original object:
```
router.post('/myEndpoint',
  (req, res, next) => {
    console.log('setting errorOnRequiredAuth to true');
    res.oidc = { ...res.oidc, getErrorOnRequiredAuth: () => true, errorOnRequiredAuth: true };
    next();
  },
  requiresAuth(),
 ...

```

**Comment by adamjmcgrath** [comment]
Hi @mostekcm 

> I want to be able to do frontend to backend calls for certain endpoints without doing a full refresh

Are you expecting `json` on these calls? If so, `fetch('/api', { headers: { accept: 'application/json' } })` will have the behaviour you're after because the SDK will only do the redirect on `requiresAuth` if the request [accepts html](https://github.com/auth0/express-openid-connect/blob/master/middleware/requiresAuth.js#L20).

If your calls are all `html`, then you can quite simply write your own mw using public apis eg.

```js
const requiresAuthApi = () => (req, res, next) => {
  if (!req.oidc.isAuthenticated()) {
    res.send(401);
  } else {
    next();
  }
};

app.get('/a', requiresAuth(), ...); // redirect when not logged in
app.get('/b', requiresAuthApi(), ...); // 401 when not logged in
```

It would be a pain to use `requiresAuth` with an additional argument because it already takes a single optional positional argument that is the default login check, so you'd need to do provide that if you want to add more arguments (which is just as much code as the 'write your own mw' solution above)

**Comment by adamjmcgrath** [comment]
Hi @mostekcm - because adding a second argument to `requiresAuth` doesn't really suit it and because we have a good solution using public APIs, I'm going to close this request. Let me know if you disagree
