### ISSUE TITLE
invalid_grant (Failed to verify code verifier)

### ISSUE THREAD

**Issue by TrevorThomp** [auth0/express-openid-connect#299]
### Describe the problem

Intermittently I keep seeing `invalid_grant (Failed to verify code verifier)` in our error logs and can't pinpoint what might be causing this. We have users being sent to our general error page if an error is thrown from our server. If they try to login again from our error page, or even just manually entering `/login` to the URL, they will be stuck in the same `invalid_grant` error until they clear their cookies and attempt a fresh login. I'm able to see the `auth_verification` cookie and it has the required properties including the `code_verifier`.

Would there be instances where the `auth_verification` cookie isn't being deleted properly in certain sessions?

I'm also able to see this in the Auth0 logs in the dashboard with a type of "Failed Exchange" and a description of "Failed to verify code verifier". 

### What was the expected behavior?

If a user's session has closed that the `auth_verification` is properly deleted, or regenerated on `/login` so the `code_verifier` is able to successfully match the code challenge from the server

### Reproduction

This error is happening intermittently. Below is the base configuration:

App URL: `https://sample.xyz.app`
Custom login domain: `https://login.xyz.app`

```JSX
/** Auth */
server.use(auth({
  authorizationParams: {
    response_type: 'code',
    audience: 'https://api.app',
    scope: 'profile openid email',
  },
  authRequired: false,
  auth0Logout: true,
  baseURL: process.env.BASE_URL,
  clientID: process.env.AUTH0_CLIENT_ID,
  clientSecret: process.env.AUTH0_CLIENT_SECRET,
  issuerBaseURL: process.env.AUTH0_DOMAIN,
  idpLogout: true,
  routes: {
    login: false
  },
  secret: process.env.SESSION_SECRET,
  session: {
    cookie: {
      domain: '.xyz.app'
    },
    store: new RedisStore({ client: redisClient }),
  }
}));
  
/** Login */
router.get('/login', (req, res) => {
  return res.oidc.login({ returnTo: '/' });
});

/** Error Handler */
server.use(function (err, req, res, next) { 
  console.error(err.stack);
  return res.redirect('/errorPage');
});
```

### Environment

`express-openid-connect: ^2.5.0,`
`connect-redis: ^4.0.3,`
`redis: 3.1.2,`

When looking at one of the logs, it looks like the user got hit with the `invalid_grant (Failed to verify code verifier)` and was sent to our error page (server error handler). When they went to `/login`, it looks the it fired off the `/authorize` followed by `/callback` and that's where it hangs and then redirects back to the error page with the same `invalid_grant` error thrown in the logs.

**Comment by adamjmcgrath** [comment]
Hi @TrevorThomp - thanks for raising this

This is probably an issue caused by concurrent tabs attempting to login at the same time. I can reproduce the issue by doing the following:

1. Click login on tab 1 but don't complete login
2. Click login on tab 2 but don't complete login
3. Go back to tab one and complete login
4. Tab 1 is using a stale `auth_verification` so will get Invalid state/nonce or "Failed to verify code verifier" for people using `code`

There are various approaches to resolving this but we find the simplest and most effective is to recommend clients handle the error and prompt the user to attempt login again, as they have an active sso session they won't be prompted to enter their credentials again on the authorization server.

**Comment by TrevorThomp** [comment]
@adamjmcgrath Thanks for the response.

I was starting to lean on the fact that it was a stale `auth_verification`, so that would make sense. Our application has certain features that are reliant on a user having multiple tabs open. We also log users out automatically after a certain period of inactivity. 

We can prompt the user in our error page to have the user login if they are sent there. However, is there any other solution that could prevent the stale `auth_verification` in the first place and remove the need for user interaction? For example, if they run across the "Failed to verify code verifier" on a login attempt, we could redirect them to login again and possibly even clear the `auth_verification` cookie so it would be fresh?

**Comment by adamjmcgrath** [comment]
> We migrated to this package from passport-auth0 and I'm guessing we didn't experience these errors because it was only reliant on the state cookie and not the PKCE

I just tested this out on the [passport-auth0 sample app](https://github.com/auth0-samples/auth0-nodejs-webapp-sample/tree/master/01-Login). And, using the steps above, the login still failed because the state in the stale cookie didn't match the state in the callback url (it hit this code path https://github.com/auth0-samples/auth0-nodejs-webapp-sample/tree/master/01-Login). Passport doesn't error in this scenario, it "fails" (I found something about this behaviour in SO https://stackoverflow.com/a/15711502) and the example app retries login - so I see 2 logins in the network panel, the second being non interactive.

You could duplicate that logic and just catch the error and retry the login again, but this does open you up to infinite redirects if the authorization code grant was invalid for a more permanent reason, that's why I prefer the user prompt.

**Comment by TrevorThomp** [comment]
Interesting. Not sure why we weren't seeing that behavior before but possibly our logs weren't showing properly. I'll go ahead and continue to handle this errors on the client and prompt the users to login if this error is thrown.

Thanks for your insight! I'm going to go ahead and close this.
