### ISSUE TITLE
New Method - Get Authorisation URL

### ISSUE THREAD

**Issue by viperz0r** [auth0/express-openid-connect#300]
### Describe the problem you'd like to have solved

It would be good if the library could provide a method to obtain the Authorization Url so I can pass it to the frontend or to 3rd Party services.

Currently, the middleware in the library will use the response.**redirect** to perform the redirection automatically, which it's not ideal for all cases.

## Alternatives and current work-arounds

At the moment, I patched the res.redirect method in order to prevent the redirection and to obtain the Authorization Url

Thanks

**Comment by adamjmcgrath** [comment]
Hi @viperz0r 

Could you tell me about your specific use case? What's wrong with just using `/login` as your url? It will redirect you to the authorisation url and has the benefit of also adding all the transaction state to your browser, so that your callback will work correctly when the user comes back to your app after logging in.

**Comment by adamjmcgrath** [comment]
Closing due to innactivity
