### ISSUE TITLE
How to provide returnUrl on /logout

### ISSUE THREAD

**Issue by balazsorban44** [auth0/express-openid-connect#35]
I have the following express implementation:

```js
// ...
express()
  .use(auth({
      required: false,
      idpLogout: true,
   }))
//...
```
I use the default `/login`, `/logout`, `/callback` routes.
`idpLogout` is set to `true`, because I want the user to be logged out from the Identity Provider as well. My problem is, that after logging out, they stay on the Identity Provider. 

**How can I pass a `returnUrl`, so the user comes back to the site?**
I tried putting this at the frontend ```<a href="/logout?returnUrl=http://example.com">Log out</a>```, but it did not help.

**Comment by joshcanhelp** [comment]
@balazsorban44 - You can pass a `returnTo` parameter (instead of `returnUrl`) to that logout URL and you should get the behavior you're looking for:

https://github.com/auth0/express-openid-connect/blob/master/lib/context.js#L97

https://github.com/auth0/express-openid-connect/blob/master/API.md#response

Just make sure that URL is saved in your Auth0 Application in the **Allowed Logout URLs**. Give that a try and, if it's not doing what you expect, ping me here. 

That's a little buried, I'll try to surface that a bit better in our documentation here 👍

**Comment by balazsorban44** [comment]
@joshcanhelp  You mean
```html
<a href="/logout?returnTo=http://localhost:8000">Log out</a>
```

or simply visiting `http://localhost:8000/logout?returnTo=http://localhost:8000`

should work? Now I am not using Auth0 but a custom Identity Provider, so I don't know if that is an issue, but there I have set the following:

![image](https://user-images.githubusercontent.com/18369201/69164420-44beb880-0af0-11ea-8684-8ad18f57ebff.png)

(Don't understand the difference between the two, so I set both 😊 Learning...)

**Comment by joshcanhelp** [comment]
Ah, ok, you're not using Auth0. The library should work fine in most cases but logout is one place where we don't have a specification to rely on. I can help in a general sense but if there is custom handling around logout for your IdP, I'm not sure how much we can do here. 

So, setting `idpLogout` to `true` in the `auth()` configuration will clue the library in to look for a `end_session_endpoint` in your IdP's discovery document. This can be found by adding `.well-known/openid-configuration` to the end of your issuer base URL. Should look something like this:

https://auth0.auth0.com/.well-known/openid-configuration

Auth0 doesn't provide that key currently so we added another configuration option `auth0Logout` to handle Auth0 specifically:

https://github.com/auth0/express-openid-connect/blob/master/lib/client.js#L54-L61

Without that turned on, handling happens in the parent library here:

https://github.com/panva/node-openid-client/blob/master/lib/client.js#L315

The **Signout URL** looks to be the place you want to save the return URL but, unless your IdP handles logout like Auth0 or how the parent library does it, you'll have to write your own logout logic.

**Comment by balazsorban44** [comment]
Looks like when the default `/logout` route is used, nothing is passed to the logout call:
https://github.com/auth0/express-openid-connect/blob/66d02df9e331f95418445b480092b5596f678e4a/middleware/auth.js#L66

Would this solve the issue?:
```diff
- router.get(config.logoutPath, (req, res) => res.openid.logout()); 
+ router.get(config.logoutPath, (req, res) => res.openid.logout({returnTo: req.query.returnTo || config.baseURL})); 
```

Also, `/login` looks "hardcoded" to `baseURL`:
https://github.com/auth0/express-openid-connect/blob/66d02df9e331f95418445b480092b5596f678e4a/middleware/auth.js#L64

```diff
- res.openid.login({ returnTo: config.baseURL }); 
+ res.openid.login({ returnTo: req.query.returnTo || config.baseURL }); 

```

I could make a PR, if you agree that this might be the problem. 🙂

**Comment by joshcanhelp** [comment]
@balazsorban44 - Apologies for the delay!

I see what you're saying on the default routes and I see that I was reading from the context method's signature rather than the URL parameters.

For the logout method, adding a URL parameter to the route would be a good improvement. I would either add the `req.query.returnTo` to [the `logout` method itself](https://github.com/auth0/express-openid-connect/blob/master/lib/context.js#L97):

```diff
- const returnURL = params.returnTo || this._config.baseURL;
+ const returnURL = params.returnTo || req.query.returnTo || this._config.baseURL;
```

... and keep the default route as it is or just pass `req.query.returnTo` in the default route and let it fall back to the base URL in `logout()` so that doesn't happen twice. Happy to accept a PR for either approach!

Taking a return URL from the query params is OK on the logout URL because they must be whitelisted in your Auth0 application. On the login route, though, if you accept arbitrary parameters, nothing at Auth0 or in your application can enforce where users end up after logging in. So someone could craft a link that uses your application to redirect to Auth0 and back, then end up on a foreign site:

```
https://yourapplication.com/login?returnTo=http://malicious.com
```

... so that URL needs to be determined and set by your application code only, not arbitrary input.

**Comment by balazsorban44** [comment]
Thanks, no problem. :smile: Will have a look at it tomorrow then!
