### ISSUE TITLE
Response type `code` without a clientSecret 

### ISSUE THREAD

**Issue by WhoAteDaCake** [auth0/express-openid-connect#352]
### Describe the problem you'd like to have solved

I'm migrating away from [angular-auth-oidc-client](https://www.npmjs.com/package/angular-auth-oidc-client), to this library and I'm a bit confused by restrictions.

When attempting to use `response_type: "code" ` the error is thrown:

> TypeError: "clientSecret" is required for a response_type that includes code

However, the previously mentioned library uses `responseType: 'code',` as part of the examples and as it's a frontend library, it contains no secrets, so why is one required here?

### Describe the ideal solution

* Undestand if there is an alternative approach, or am is my understanding wrong
* Ability to login via Local Login page -> OpenId provider -> Account selection -> callback to Local login page

Sorry if this not the right place to ask, but if you have any relevant information you could share, it be really appreciated

**Comment by WhoAteDaCake** [comment]
I assume this is explained by: https://community.auth0.com/t/authorization-code-flow-without-client-secret/34022/2 ?

**Comment by frederikprijck** [comment]
Hey @WhoAteDaCake , that is correct. 

When using `response_type: "code"` from a web application, you are required to send a client secret.
This is different with Angular applications, we have an SDK for Angular that doesn't require you to use a client secret: https://github.com/auth0/auth0-angular.

What's the specific reason you are replacing `angular-auth-oidc-client` with `express-openid-connect` instead of `auth0-angular`?

**Comment by WhoAteDaCake** [comment]
Thank you very much for taking your time with the response, my knowledge is quite limited, that's why I went for a direct comparison.
