### ISSUE TITLE
Bump jose version

### ISSUE THREAD

**Issue by iotaaxel** [auth0/express-openid-connect#354]
### Describe the problem you'd like to have solved

I would like to have the [ jose](https://www.npmjs.com/package/jose) dependency version updated. I am resolving a dependency conflict on a repo and would like to use a newer version.

### Describe the ideal solution

Ideally, a pull request would just need to change `package.json` and `package-lock.json`. 

## Alternatives and current work-arounds

I'm considering having an optional dependency for my project to help with versioning and be careful when handling scope for different sections of code.

### Additional information, if any

Likely, the tests might need to be updated due to potential breaking changes.

**Comment by adamjmcgrath** [comment]
Hi @iotaaxel - thanks for raising this

Bumping jose@3 support a minimum of Node 12 (https://github.com/panva/jose/issues/262) and this SDK supports Node 10 (https://github.com/auth0/express-openid-connect/blob/master/package.json#L72)

So we wont be upgrading to jose@3 until we release a new major of this SDK. I can't tell you when that will be, but we will upgrade jose when we cut a new major.

**Comment by adamjmcgrath** [comment]
Thanks for sharing that @acberk an @dumaron 

jose@2 is still providing security fixes and there are no bugs with jose@2 that are affecting this SDK AFAIK

And since bun aims for ["complete Node.js compatibility"](https://bun.sh/docs/runtime/nodejs-apis#:~:text=Bun%20aims%20for%20complete%20Node.js%20API%20compatibility.) and jose@2 works with Node.js - I assume there is a bug with Bun that is preventing jose@2 from working.

We do want to upgrade jose, we'd just like to do a couple of other things if we're making a new major - and we need to schedule this in - your feedback is helpful though so thank you

**Comment by dumaron** [comment]
Thanks for the answer @adamjmcgrath .
Here's [the issue on the Bun repo](https://github.com/oven-sh/bun/issues/5122) related to `jose`, just in case someone is interested in keeping track of their progress.
