### ISSUE TITLE
On New setup Window 10 Issuer.discover() failed error

### ISSUE THREAD

**Issue by gauravverma029** [auth0/express-openid-connect#360]
### Describe the problem

<img width="599" alt="Screenshot 2022-06-12 174657" src="https://user-images.githubusercontent.com/4488516/173247753-0bcd3ae4-1917-4d4b-bced-498b6fc6ae2d.png">

### Reproduction

- Step 1..
- Step 2..
- ...

### Environment

- **Version of this library used:**
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by adamjmcgrath** [comment]
Hi @gauravverma029 - thanks for raising this

> RequestError: unable to get local issuer certificate

Looks like your Node server can't access your issuer's discovery document. What value do you have for `ISSUER_BASE_URL` and can you access `${ISSUER_BASE_URL}/.well-known/openid-configuration` from the command line using something like curl?

**Comment by gauravverma029** [comment]
Yes from Terminal , i got this response 
<img width="960" alt="Screenshot 2022-06-13 112821_____" src="https://user-images.githubusercontent.com/4488516/173323672-e00051fc-4b96-4b7b-99c3-9a39f4d3d6dc.png">

**Comment by gauravverma029** [comment]
Node server can't access your issuer's discovery document (What can we do here) do we need to set some permission on window laptop

**Comment by adamjmcgrath** [comment]
@gauravverma029 - I don't know why your Node server can't access a resource on the web, there's nothing wrong with the resource, since you're able to access it form curl.

Couple of suggestions:
- you may be passing the wrong url as ISSUER_BASE_URL - double check that the value is the same as the one you used in your curl command
- Your Node server may be configured to use a proxy to contact the internet which is causing the issue

Either way, I don't think there's nothing that the SDK can do here
