### ISSUE TITLE
Login flow in two tabs at the same time results in state mismatch error

### ISSUE THREAD

**Issue by jbrantly** [auth0/express-openid-connect#43]
### Description

Two browser tabs going through a login process at the same time can result in a state mismatch error.

### Reproduction

1. Open your application in tab 1 and be redirected to the identity provider
2. Open your application in tab 2 and be redirected to the identity provider
3. Attempt to finish login process in tab 1

Actual result: A state mismatch error
Expected result: A successful login

### Further Details

It appears that this middleware stores the nonce and state in a cookie, which when shared across tabs (or even across requests), invalidates previous login attempts because the previous values are overwritten. We also saw a similar issue where asset requests to our app were triggering the auth flow (this was due to a misconfiguration on our part) and invalidating the current login flow since new nonces/state were issued.

Potentially related issues:
https://github.com/aspnet/Security/issues/179

**Comment by jbrantly** [comment]
It appears that some other libraries use multiple named cookies with a known prefix to solve this problem. That can lead to other issues though, such as Request Too Long, if a bunch of old cookies pile up without being deleted. Solutions to this include setting proper expiration for cookies (already done here) and managing the max count of the cookies with a FIFO strategy.

**Comment by joshcanhelp** [comment]
@jbrantly - Appreciate the report here and apologies for the delay in getting back to you. 

As you mentioned, this is a common issue in cross-domain authentication. I don't know of a great universal solution here, besides what you've mentioned. The cause of this issue is part of what nonce and state are meant to prevent. 

We might be able to tighten up the expiration time but that's only partially effective and starts to have its own issues the shorter it gets. 

One option might be a custom middleware that checks stored state against returned state and, if both exist but are different, redirects to the IdP to login link again. If SSO is being used, this will be one more round trip but should end up with a successful link. 

I'm going to close this for now but if anyone has preferred strategy here, I'm happy to discuss.

**Comment by jbrantly** [comment]
Would you be open to a PR with something along the "multiple cookies" solution? It wasn't clear if the `wontfix` is for philosophical reasons or effort reasons.

**Comment by jbrantly** [comment]
Quick ping on this issue. My team is willing to contribute here, especially with the 0.6.0 release which I think would make the cookie handling easier, but don't necessarily want to put in the effort if there's no chance of a merge.
@joshcanhelp

**Comment by joshcanhelp** [comment]
@jbrantly - Apologies, this slipped through the cracks! I'd be happy to review a PR. The smaller the better at first to make sure that the approach will work. 

Thank you!

**Comment by Damien-G1** [comment]
Just a heads up, I'm still running into this issue with 2.16.0. Anyone else seeing this? Do you want more info or should I start a new thread?

I'm currently redirecting them to the baseURL using an express error handler, relying on them having the right cookies to complete the login. It's not the best solution.

Thanks!

**Comment by karthikeyan-murugan** [comment]
I'm also looking for a solution to this problem.

**Comment by alexandis** [comment]
I am having probably a similar issue.
1) Angular app with OpenID server authentication - a user is authenticated - opened in tab #1.
2) I open this app in tab #2. So far so good.
3) I press "Logout" (we use **ABP** framework-based solution, do not want to dig into tech details so far) and due to the following code both tabs are eventually redirected to Login form of OpenID server:
```
this.window.addEventListener('storage', event => {
  if (event.key === 'access_token' && event.newValue === null) {
    this.window.location.reload();
  }
});
```
4) I login in tab #1.
5) I try to login in tab #2. Getting the exception from OpenID server:

> Antiforgery token validation failed. The provided antiforgery token was meant for a different claims-based user than the current user.
> Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The provided antiforgery token was meant for a different claims-based user than the current user.
>    at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateTokens(HttpContext httpContext, AntiforgeryTokenSet antiforgeryTokenSet)
>    at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
>    at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
