### ISSUE TITLE
the "originalUrl" is not used as the default "returnTo" url, the baseUrl is

### ISSUE THREAD

**Issue by jordanst3wart** [auth0/express-openid-connect#479]
### Checklist

- [X] The issue can be reproduced in the [express-openid-connect sample app](https://github.com/auth0-samples/auth0-express-webapp-sample/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/express-openid-connect#readme), [Examples](https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/express-openid-connect/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/express-openid-connect/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/express-openid-connect/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The baseUrl is used as the returnTo value as a default, when it should be the "originalUrl" the request came from.

The error is here. It should use returnTo if defined or originalUrl:
https://github.com/auth0/express-openid-connect/blob/1d33b743fe9281c4cbf6f0d18f761b41502329de/middleware/auth.js#L42

This is a regression of this fix:
https://github.com/auth0/express-openid-connect/pull/95

I believe the originalUrl is the "referrer" header in the Get login request.

### Reproduction

Try logging into an application. The state should include a returnTo value of the baseUrl, and not the original url the request was from.

### express-openid-connect version

any v2 version

### Express version

any

### Node.js version

any

**Comment by adamjmcgrath** [comment]
Hi @jordanst3wart - thanks for raising this

This behaviour is as designed, we don't use the referrer header in the returnTo by default because the referrer header can be a third party (eg if google linked to your login page, you would return to google after login) - if you want this behaviour you can override the default login route behaviour, see https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md#3-route-customization

> The baseUrl is used as the returnTo value as a default, when it should be the "originalUrl" the request came from.
> The error is here. It should use returnTo if defined or originalUrl:

`originalUrl` in this instance is the `/login` route - so if you returned to that page after login you would be stuck in an infinite loop

> This is a regression of this fix: https://github.com/auth0/express-openid-connect/pull/95

There is no regression, this behaviour works as designed. When you protect a route with `requiresAuth` - you will be returned to that route after login (this is the behaviour that was fixed in https://github.com/auth0/express-openid-connect/pull/95) see https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md#2-require-authentication-for-specific-routes

**Comment by jordanst3wart** [comment]
Yeah, the number 2. sample works as expected.

Thanks for your time! Closing
